### ISSUE TITLE
Open Channel/ React-Channel metadata and metacounter

### ISSUE THREAD

**Issue by octa-george** [sendbird/sendbird-chat-sample-react#13]
Users can store and manage (create, update, retrieve, delete) additional information such as the number of likes or the background color of a channel.
Users can manage (create, update, increase, decrease) additional information to channels such as the tracking number of likes with channel metacounter

**Comment by AAPK-code** [comment]
@chrischabot @james-a-rob 

Blocked because of an issue with meta counter:
Method `channel.getAllMetaCounters` sends wrong network requests.

https://user-images.githubusercontent.com/67925765/172158657-87d38ec2-d6e1-4c1e-a8d3-eab0d00297dd.mov


`getAllMetaCounters`  - send a request to `https://api-.... ban?keys=` I guess this is getting banned users.
